services:

  postgres:
    image: postgres:18-alpine
    container_name: coatingminer_postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - pg_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    container_name: coatingminer_api
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: coatingminer_redis
    ports:
      - '6379:6379'

volumes:
  pg_data: